### ISSUE TITLE
Cant build the sandfly-filescan

### ISSUE THREAD

**Issue by michael2425** [sandflysecurity/sandfly-filescan#4]
Hi, 

I'm kept receiving the following error whenever i tried to build using Go:

can't load package: package sandfly-filescan: cannot find package "sandfly-filescan" in any of:
	/usr/lib/go-1.13/src/sandfly-filescan (from $GOROOT)
	/root/go/src/sandfly-filescan (from $GOPATH)

**Comment by julesblau** [comment]
I am also having this same issue. I tried adding the sandfly-filescan package to the /usr/lib/go-1.18/src folder but do not have ownership permissions to do so. Any other suggestions on how I can build sandfly-filescan? Or was this issue resolved?

**Comment by craighrowland** [comment]
Updated to use go modules with cleaner build script. Try again.
